100:
  model:
    per: atom
    regression:
      krr:
        centering: false
        kernel:
          kernel_global:
            kernelf:
              gaussian:
                ls: 2.0
        nl: 1.3486991523486091e-06
    representation:
      mbtr_2:
        acc: 0.001
        aindexf: full
        broadening: 0.02209708691207961
        eindexf: full
        elems: [12, 13, 22, 23, 26, 27, 28, 29, 41, 47]
        flatten: true
        geomf: 1/dot
        norm:
          simple:
            scale: 1.0
        num: 100
        start: -0.01
        stop: 0.19
        weightf:
          exp_-1/identity^2:
            ls: 64.0
250:
  model:
    per: atom
    regression:
      krr:
        centering: false
        kernel:
          kernel_global:
            kernelf:
              gaussian:
                ls: 0.25
        nl: 0.000244140625
    representation:
      mbtr_2:
        acc: 0.001
        aindexf: full
        broadening: 0.015625
        eindexf: full
        elems: [12, 13, 22, 23, 26, 27, 28, 29, 41, 47]
        flatten: true
        geomf: 1/distance
        norm:
          simple:
            scale: 1.0
        num: 100
        start: -0.02
        stop: 0.45
        weightf:
          exp_-1/identity^2:
            ls: 16.0
650:
  model:
    per: atom
    regression:
      krr:
        centering: false
        kernel:
          kernel_global:
            kernelf:
              gaussian:
                ls: 0.125
        nl: 0.00048828125
    representation:
      mbtr_2:
        acc: 0.001
        aindexf: full
        broadening: 0.015625
        eindexf: full
        elems: [12, 13, 22, 23, 26, 27, 28, 29, 41, 47]
        flatten: true
        geomf: 1/distance
        norm:
          simple:
            scale: 1.0
        num: 100
        start: -0.02
        stop: 0.45
        weightf:
          exp_-1/identity:
            ls: 1.0
1600:
  model:
    per: atom
    regression:
      krr:
        centering: false
        kernel:
          kernel_global:
            kernelf:
              gaussian:
                ls: 0.1767766952966369
        nl: 3.0517578125e-05
    representation:
      mbtr_2:
        acc: 0.001
        aindexf: full
        broadening: 0.015625
        eindexf: full
        elems: [12, 13, 22, 23, 26, 27, 28, 29, 41, 47]
        flatten: true
        geomf: 1/distance
        norm:
          simple:
            scale: 1.0
        num: 100
        start: -0.02
        stop: 0.45
        weightf:
          exp_-1/identity^2:
            ls: 16.0
4000:
  model:
    per: atom
    regression:
      krr:
        centering: false
        kernel:
          kernel_global:
            kernelf:
              gaussian:
                ls: 0.0625
        nl: 0.000244140625
    representation:
      mbtr_2:
        acc: 0.001
        aindexf: full
        broadening: 0.015625
        eindexf: full
        elems: [12, 13, 22, 23, 26, 27, 28, 29, 41, 47]
        flatten: true
        geomf: 1/distance
        norm:
          simple:
            scale: 1.0
        num: 100
        start: -0.02
        stop: 0.45
        weightf:
          exp_-1/identity:
            ls: 2.0
10000:
  model:
    per: atom
    regression:
      krr:
        centering: false
        kernel:
          kernel_global:
            kernelf:
              gaussian:
                ls: 0.125
        nl: 1.0789593218788873e-05
    representation:
      mbtr_2:
        acc: 0.001
        aindexf: full
        broadening: 0.011048543456039806
        eindexf: full
        elems: [12, 13, 22, 23, 26, 27, 28, 29, 41, 47]
        flatten: true
        geomf: 1/distance
        norm:
          simple:
            scale: 1.0
        num: 100
        start: -0.02
        stop: 0.45
        weightf:
          exp_-1/identity:
            ls: 2.0

