path: ""
fileQM9: 'qm9_compl.pkl'
test_ref: "Fold5_Round10_Sample4000_a1_mbtr23"

Fold5_Round10_Sample4000_a1_mbtr23:
  num_folds: 5
  num_rounds: 10
  column_y: 'U0'
  qtd_sample_qm9: 4000
  gamma_a: 1
  gamma_variance: 34
  model:
      per: mol
      regression:
        krr:
          centering: false
          kernel:
            kernel_global:
              kernelf:
                gaussian:
                  ls: 22.627416997969522
          nl: 1.3486991523486091e-06
      representation:
        composed:
          reps: [{mbtr_2: {acc: 0.001, aindexf: full, broadening: 0.025635479875238686,
                  eindexf: full, elems: [1, 6, 7, 8, 9], flatten: true, geomf: 1/distance,
                  norm: {none: {}}, num: 100, start: -0.05, stop: 1.1, weightf: identity^2}},
                 {mbtr_3: {acc: 0.001, aindexf: full, broadening: 0.03589682359365735, eindexf: full,
                  elems: [1, 6, 7, 8, 9], flatten: true, geomf: dot/dotdot, norm: {none: {}},
                  num: 100, start: -1.14, stop: 1.14, weightf: 1/dotdotdot}}]





