path: ""
fileQM9: 'qm9_compl.pkl'
test_ref: "Fold5_Round10_Sample650_am_sf23"

Fold5_Round10_Sample650_am_sf23:
  num_folds: 5
  num_rounds: 10
  column_y: 'U0'
  qtd_sample_qm9: 650
  gamma_a: 32
  gamma_variance: 34
  model:
      per: mol
      regression:
        krr:
          centering: false
          kernel:
            kernel_atomic:
              kernelf:
                gaussian:
                  ls: 8.0
              norm: false
          nl: 0.0001220703125
      representation:
        composed:
          reps: [{sf:
                    {dim: null,
                     elemental: [],
                     elems: [1, 6, 7, 8, 9],
                     universal: [{rad_shifted: {cutoff: 3, n: 8}},
                                 {rad_centered: {cutoff: 3, n: 6}},
                                 {ang: {cutoff: 9, eta: 0.25, lambd: 1, zeta: 1}}, 
                                 {ang: {cutoff: 4, eta: 0.00017263349150062197, lambd: -1, zeta: 1}}, 
                                 null,
                                 {ang: {cutoff: 3, eta: 0.00017263349150062197, lambd: -1, zeta: 2}}, 
                                 {ang: {cutoff: 9, eta: 1.0, lambd: 1, zeta: 4}}, 
                                 {ang: {cutoff: 5, eta: 0.000244140625, lambd: -1, zeta: 4}} 
                                ]
                    }
                  }
                 ]



      
