path: ""
fileQM9: 'qm9_compl.pkl'
test_ref: "Fold5_Round10_Sample1600_ax_sf23"

Fold5_Round10_Sample1600_ax_sf23:
  num_folds: 5
  num_rounds: 10
  column_y: 'U0'
  qtd_sample_qm9: 1600
  gamma_a: 120
  gamma_variance: 34
  model:
      per: mol
      regression:
        krr:
          centering: false
          kernel:
            kernel_atomic:
              kernelf:
                gaussian:
                  ls: 8.0
              norm: false
          nl: 9.5367431640625e-07
      representation:
        composed:
          reps: [{sf:
                    {dim: null,
                     elemental: [],
                     elems: [1, 6, 7, 8, 9],
                     universal: [{rad_shifted: {cutoff: 3, n: 6}},
                                 {rad_centered: {cutoff: 3, n: 3}},
                                 {ang: {cutoff: 2, eta: 0.0009765625, lambd: 1, zeta: 1}}, 
                                 {ang: {cutoff: 3, eta: 0.000244140625, lambd: -1, zeta: 1}},
                                 null, null, 
                                 {ang: {cutoff: 2, eta: 7.62939453125e-06, lambd: 1, zeta: 4}}, 
                                 null
                                ]
                    }
                  }
                 ]



      
